### ISSUE TITLE
ICDAR2013 groundtruth xml file

### ISSUE THREAD

**Issue by juntingzh** [lluisgomez/TextProposals#1]
Hi!

I am interested in reproducing the text proposal generation results on ICDAR 2013 dataset. The dataset I got has a different format of the ground truth data, which is provided in a single text file for each image. 

I searched online but found no place to download the ICDAR2013/test_locations.xml  or ICDAR2013/training_locations.xml anymore. In order to evaluate the results, could you please share the xml files with me?

Many thanks!

**Comment by lluisgomez** [comment]
I've just commited the xml files for ICDAR2013 train/test sets. See e03ec1c
