### ISSUE TITLE
Model is not available

### ISSUE THREAD

**Issue by jugg1024** [lluisgomez/TextProposals#3]
https://www.dropbox.com/sh/vsvh3pu8s0y2lno/AABoBjazgRfllCnZw8H36xmna?dl=0 return ERR_CONNECTION_TIMED_OUT. 
Can you send the model file and prototxt to ligen2014@ia.ac.cn

**Comment by lluisgomez** [comment]
Looks like Dropbox is not the right solution to share large CNN models :)  I've just updated the README.md file with a new URL.
