### ISSUE TITLE
Use of undeclared identifier in fast_clustering code

### ISSUE THREAD

**Issue by lkorsos1** [lluisgomez/TextProposals#4]
Hey, love the ideas in this code!  Was trying to run it and I've been running into the following issue when trying to run make.  I'm wondering if I'm just missing something super obvious.  Thanks a ton!

```
LASZLOs-MBP:TextProposals laszlo$ make
Scanning dependencies of target eval_SVT
[  2%] Building CXX object CMakeFiles/eval_SVT.dir/fast_clustering.cpp.o
/Users/laszlo/TextProposals/fast_clustering.cpp:1927:5: error: use of undeclared identifier 'free'
    free(V);
    ^
1 error generated.
make[2]: *** [CMakeFiles/eval_SVT.dir/fast_clustering.cpp.o] Error 1
make[1]: *** [CMakeFiles/eval_SVT.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by lluisgomez** [comment]
Ops! Can you please provide information about your operative system and architecture to reproduce the problem? Paste also the output of "cmake ."

**Comment by dudullz** [comment]
@lkorsos1 just add the following line at the top of `fast_clustering.cpp`
#include <stdlib.h>

**Comment by lluisgomez** [comment]
@dudullz Thanks!
