### ISSUE TITLE
Too many results from MSER detections

### ISSUE THREAD

**Issue by dudullz** [lluisgomez/TextProposals#5]
Hi @lluisgomez , I've compiled the codes (incl. CNN version with caffe/gpu etc.) successfully. 

However when I tried with some simple images (e.g. lenna.jpg or SVT ) I'm getting way too many MSER regions, around 1,000 averagely. The final result for `img2hierarchy lenna.jpg` are just meaningless. What's the parameters should be passed to MSER::create(...)?

Also, is there any way to visualise the final result as in the paper (e.g. Fig. 3)?

Many thanks!

**Comment by lluisgomez** [comment]
@dudullz, 

all code in this repository is aimed to reproduce the quantitative results shown in the paper. You do not need to change any parameter for this.

The example you are executing `img2hierarchy` only prints to stdout the list of _all_ text proposals for a given image. It allows to reproduce the plots in Figures 5 and 7 of the paper (as explained in README.md). Text proposals are in the range of thousands, and they are just a list of ranked "hypothesis" (candidate text regions) for the given image. The goal is to achieve very high detection recall, but we do not care about precision at all here.

There is no code to visualize the best proposals as in Figure 3. But you can easily find the best proposal by matching ground-truth bounding boxes with the list provided by `img2hierarchy` (in terms of best IoU).

Btw, visualization makes more sense for the end to end pipeline than for the proposals bounding boxes. You can easily visualize end-to-end results with `img2hierarchy_cnn` , just uncomment line 551 in main_cnn.cpp and add `imshow("",src); waitKey(-1);` at the end of main().
