### ISSUE TITLE
Getting too many errors

### ISSUE THREAD

**Issue by NewHope2016** [lluisgomez/TextProposals#8]
Hi @lluisgomez 

Thank you for the code ...i followed all your instructions to successfuly run it...but i'm getting this errors :( 

Mohds-MacBook-Air:TextProposals-master mohd$ make

[  2%] Building CXX object CMakeFiles/eval_SVT.dir/eval_SVT.cpp.o

/Users/mohd/Downloads/TextProposals-master/eval_SVT.cpp:53:3: error: 

```
  unknown type name 'shared_ptr'
```

  shared_ptr<Net<float>>  net_;

  ^

/Users/mohd/Downloads/TextProposals-master/eval_SVT.cpp:53:13: error: 

```
  expected member name or ';' after declaration specifiers
```

  shared_ptr<Net<float>>  net_;

``` ^

/Users/mohd/Downloads/TextProposals-master/eval_SVT.cpp:73:3: error: use

      of undeclared identifier 'net_'

  net_.reset(new Net<float>(model_file, TEST));

  ^

/Users/mohd/Downloads/TextProposals-master/eval_SVT.cpp:74:3: error: use

      of undeclared identifier 'net_'

  net_->CopyTrainedLayersFrom(trained_file);

  ^

/Users/mohd/Downloads/TextProposals-master/eval_SVT.cpp:76:12: error: 

      use of undeclared identifier 'net_'; did you mean 'new'?

  CHECK_EQ(net_->num_inputs(), 1) << "Network should have exactly one input.";

           ^~~~

           new

/usr/local/include/glog/logging.h:765:48: note: expanded from macro 'CHECK_EQ'

#define CHECK_EQ(val1, val2) CHECK_OP(_EQ, ==, val1, val2)

                                               ^

/usr/local/include/glog/logging.h:741:26: note: expanded from macro 'CHECK_OP'

  CHECK_OP_LOG(name, op, val1, val2, google::LogMessageFatal)

                         ^

/usr/local/include/glog/logging.h:733:44: note: expanded from macro

      'CHECK_OP_LOG'

             google::GetReferenceableValue(val1),        \

                                           ^

/Users/mohd/Downloads/TextProposals-master/eval_SVT.cpp:76:16: error: 

      expected a type

  CHECK_EQ(net_->num_inputs(), 1) << "Network should have exactly one input.";

               ^

/Users/mohd/Downloads/TextProposals-master/eval_SVT.cpp:77:12: error: 

      use of undeclared identifier 'net_'; did you mean 'new'?

  CHECK_EQ(net_->num_outputs(), 1) << "Network should have exactly one ...

           ^~~~

           new

/usr/local/include/glog/logging.h:765:48: note: expanded from macro 'CHECK_EQ'

#define CHECK_EQ(val1, val2) CHECK_OP(_EQ, ==, val1, val2)

                                               ^

/usr/local/include/glog/logging.h:741:26: note: expanded from macro 'CHECK_OP'

  CHECK_OP_LOG(name, op, val1, val2, google::LogMessageFatal)

                         ^

/usr/local/include/glog/logging.h:733:44: note: expanded from macro

      'CHECK_OP_LOG'

             google::GetReferenceableValue(val1),        \

                                           ^

/Users/mohd/Downloads/TextProposals-master/eval_SVT.cpp:77:16: error: 

      expected a type

  CHECK_EQ(net_->num_outputs(), 1) << "Network should have exactly one ...

               ^

/Users/mohd/Downloads/TextProposals-master/eval_SVT.cpp:79:30: error: 

      use of undeclared identifier 'net_'; did you mean 'new'?

  Blob<float>* input_layer = net_->input_blobs()[0];

                             ^~~~

                             new

/Users/mohd/Downloads/TextProposals-master/eval_SVT.cpp:79:34: error: 

      expected a type

  Blob<float>* input_layer = net_->input_blobs()[0];

                                 ^

/Users/mohd/Downloads/TextProposals-master/eval_SVT.cpp:88:3: error: use

      of undeclared identifier 'net_'

  net_->Reshape();

  ^

/Users/mohd/Downloads/TextProposals-master/eval_SVT.cpp:97:31: error: 

      use of undeclared identifier 'net_'; did you mean 'new'?

  Blob<float>* output_layer = net_->output_blobs()[0];

                              ^~~~

                              new

/Users/mohd/Downloads/TextProposals-master/eval_SVT.cpp:97:35: error: 

      expected a type

  Blob<float>* output_layer = net_->output_blobs()[0];

                                  ^

/Users/mohd/Downloads/TextProposals-master/eval_SVT.cpp:106:30: error: 

      use of undeclared identifier 'net_'; did you mean 'new'?

  Blob<float>* input_layer = net_->input_blobs()[0];

                             ^~~~

                             new

/Users/mohd/Downloads/TextProposals-master/eval_SVT.cpp:106:34: error: 

      expected a type

  Blob<float>* input_layer = net_->input_blobs()[0];

                                 ^

/Users/mohd/Downloads/TextProposals-master/eval_SVT.cpp:114:5: error: 

      use of undeclared identifier 'net_'

    net_->Reshape();

    ^

/Users/mohd/Downloads/TextProposals-master/eval_SVT.cpp:128:3: error: 

      use of undeclared identifier 'net_'

  net_->ForwardPrefilled();

  ^

/Users/mohd/Downloads/TextProposals-master/eval_SVT.cpp:131:31: error: 

      use of undeclared identifier 'net_'; did you mean 'new'?

  Blob<float>* output_layer = net_->output_blobs()[0];

                              ^~~~

                              new

/Users/mohd/Downloads/TextProposals-master/eval_SVT.cpp:131:35: error: 

      expected a type

  Blob<float>* output_layer = net_->output_blobs()[0];

                                  ^

/Users/mohd/Downloads/TextProposals-master/eval_SVT.cpp:269:18: warning: 

      expression result unused [-Wunused-value]

            for( xml_object; xml_object; xml_object=xml_object->NextSib...

                 ^~~~~~~~~~

fatal error: too many errors emitted, stopping now [-ferror-limit=]

1 warning and 20 errors generated.

make[2]: *** [CMakeFiles/eval_SVT.dir/eval_SVT.cpp.o] Error 1

make[1]: *** [CMakeFiles/eval_SVT.dir/all] Error 2






```

**Comment by codecolony** [comment]
I'm getting the same errors :(

**Comment by codecolony** [comment]
Ok, I resolved it by using proper namespace for shared_ptr object. Open the file that is causing the error and replace 'shared_ptr' with 'boost::shared_ptr'. Then continue compiling.

**Comment by NewHope2016** [comment]
Thank you ...I'm getting the following error now ... can u help please

Scanning dependencies of target eval_SVT
[  2%] Building CXX object CMakeFiles/eval_SVT.dir/eval_SVT.cpp.o
/Users/mohd/Downloads/TextProposals-master/eval_SVT.cpp:267:18: warning: 
      expression result unused [-Wunused-value]
            for( xml_object; xml_object; xml_object=xml_object->NextSib...
                 ^~~~~~~~~~
/Users/mohd/Downloads/TextProposals-master/eval_SVT.cpp:328:44: error: 
      too many arguments to function call, expected single argument
      'detectorType', have 5 arguments
  ...= MSER::create(delta,(int)(0.00002_img_area),(int)(0.11_img_area),55,0.);
       ~~~~~~~~~~~~       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/opencv2/features2d/features2d.hpp:182:13: note: 'create'
      declared here
    CV_WRAP static Ptr<FeatureDetector> create( const string& detectorType );
            ^
/Users/mohd/Downloads/TextProposals-master/eval_SVT.cpp:379:18: error: 
      no member named 'detectRegions' in 'cv::MSER'
        cv_mser->detectRegions(channels[c], contours, mser_bboxes);

**Comment by codecolony** [comment]
Which version of OpenCV do you have? Looks like 'detectRegions' is missing in your version.

**Comment by NewHope2016** [comment]
Thank you ..Codecolony i did résolve the prb but now i'm getting this error that seem difficult to understand 
[  2%] Linking CXX executable eval_SVT
ld: library not found for -libcaffe.so
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by codecolony** [comment]
Rename libcaffe.so to libcaffe.dylib in CMakeLists and it will be resolved.

**Comment by NewHope2016** [comment]
Thanx @codecolony  that work but i'm still getting other error 
Undefined symbols for architecture x86_64:
  "cv::FileStorage::FileStorage(cv::String const&, int, cv::String const&)", referenced from:
      cv::Ptrcv::ml::Boost cv::Algorithm::loadcv::ml::Boost(cv::String const&, cv::String const&) in agglomerative_clustering.cpp.o
  "cv::FileNodeIterator::readRaw(cv::String const&, unsigned char_, unsigned long)", referenced from:
      cv::internal::VecReaderProxy<int, 1>::operator()(std::__1::vector<int, std::__1::allocator<int> >&, unsigned long) const in agglomerative_clustering.cpp.o
  "cv::distanceTransform(cv::_InputArray const&, cv::_OutputArray const&, int, int, int)", referenced from:
      Region::extract_features(cv::Mat&, cv::Mat&, cv::Mat&, cv::Mat&, bool_) in region.cpp.o
  "cv::ml::Boost::create()", referenced from:
      cv::Ptrcv::ml::Boost cv::Algorithm::loadcv::ml::Boost(cv::String const&, cv::String const&) in agglomerative_clustering.cpp.o
  "cv::MSER::create(int, int, int, double, double, int, double, double, int)", referenced from:
      _main in eval_SVT.cpp.o
  "cv::read(cv::FileNode const&, cv::String&, cv::String const&)", referenced from:
      HCluster::read(cv::FileNode const&) in agglomerative_clustering.cpp.o
  "cv::read(cv::FileNode const&, double&, double)", referenced from:
      HCluster::read(cv::FileNode const&) in agglomerative_clustering.cpp.o
  "cv::read(cv::FileNode const&, float&, float)", referenced from:
      HCluster::read(cv::FileNode const&) in agglomerative_clustering.cpp.o
  "cv::read(cv::FileNode const&, int&, int)", referenced from:
      HCluster::read(cv::FileNode const&) in agglomerative_clustering.cpp.o
  "cv::error(int, cv::String const&, char const_, char const_, int)", referenced from:
      HierarchicalClustering::HierarchicalClustering(std::__1::vector<Region, std::__1::allocator<Region> >&) in agglomerative_clustering.cpp.o
      HCluster::write(cv::FileStorage&) const in agglomerative_clustering.cpp.o
  "cv::write(cv::FileStorage&, cv::String const&, double)", referenced from:
      HCluster::write(cv::FileStorage&) const in agglomerative_clustering.cpp.o
  "cv::write(cv::FileStorage&, cv::String const&, float)", referenced from:
      HCluster::write(cv::FileStorage&) const in agglomerative_clustering.cpp.o
  "cv::write(cv::FileStorage&, cv::String const&, int)", referenced from:
      HCluster::write(cv::FileStorage&) const in agglomerative_clustering.cpp.o
  "cv::String::deallocate()", referenced from:
      _main in eval_SVT.cpp.o
      HierarchicalClustering::HierarchicalClustering(std::__1::vector<Region, std::__1::allocator<Region> >&) in agglomerative_clustering.cpp.o
      HCluster::write(cv::FileStorage&) const in agglomerative_clustering.cpp.o
      HCluster::read(cv::FileNode const&) in agglomerative_clustering.cpp.o
      cv::Ptrcv::ml::Boost cv::Algorithm::loadcv::ml::Boost(cv::String const&, cv::String const&) in agglomerative_clustering.cpp.o
      cv::internal::VecReaderProxy<int, 1>::operator()(std::__1::vector<int, std::__1::allocator<int> >&, unsigned long) const in agglomerative_clustering.cpp.o
  "cv::String::allocate(unsigned long)", referenced from:
      _main in eval_SVT.cpp.o
      HierarchicalClustering::HierarchicalClustering(std::__1::vector<Region, std::__1::allocator<Region> >&) in agglomerative_clustering.cpp.o
      HCluster::write(cv::FileStorage&) const in agglomerative_clustering.cpp.o
      cv::internal::VecReaderProxy<int, 1>::operator()(std::__1::vector<int, std::__1::allocator<int> >&, unsigned long) const in agglomerative_clustering.cpp.o
  "cv::imread(cv::String const&, int)", referenced from:
      _main in eval_SVT.cpp.o
  "cv::internal::WriteStructContext::WriteStructContext(cv::FileStorage&, cv::String const&, int, cv::String const&)", referenced from:
      HCluster::write(cv::FileStorage&) const in agglomerative_clustering.cpp.o
  "cv::internal::WriteStructContext::~WriteStructContext()", referenced from:
      HCluster::write(cv::FileStorage&) const in agglomerative_clustering.cpp.o
  "cv::operator<<(cv::FileStorage&, cv::String const&)", referenced from:
      HCluster::write(cv::FileStorage&) const in agglomerative_clustering.cpp.o
  "cv::FileStorage::operator[](cv::String const&) const", referenced from:
      cv::Ptrcv::ml::Boost cv::Algorithm::loadcv::ml::Boost(cv::String const&, cv::String const&) in agglomerative_clustering.cpp.o
  "cv::FileNode::size() const", referenced from:
      HCluster::read(cv::FileNode const&) in agglomerative_clustering.cpp.o
      cv::Ptrcv::ml::Boost cv::Algorithm::loadcv::ml::Boost(cv::String const&, cv::String const&) in agglomerative_clustering.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: **\* [eval_SVT] Error 1
make[1]: **\* [CMakeFiles/eval_SVT.dir/all] Error 2

**Comment by codecolony** [comment]
All these errors are coming out of OpenCV. I suggest you uninstall your opencv and install 3.x.x along with contrib modules and try again. Sorry, I don't have a better suggestion for your current problem.

**Comment by NewHope2016** [comment]
Many tanks @codecolony  i did it and it work but :( error in execution now:
Mohds-MacBook-Air:TextProposals-master mohd$ ./img2hierarchy TO50.JPG
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in ipp_cvtColor, file /Users/mohd/Music/opencv-3.1.0/modules/imgproc/src/color.cpp, line 7456
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /Users/mohd/Music/opencv-3.1.0/modules/imgproc/src/color.cpp:7456: error: (-215) scn == 3 || scn == 4 in function ipp_cvtColor

Abort trap: 6
Mohds-MacBook-Air:TextProposals-master mohdi$ ./img2hierarchy_cnn TO50.JPG
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:537] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 1964480478
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in ipp_cvtColor, file /Users/mohd/Music/opencv-3.1.0/modules/imgproc/src/color.cpp, line 7456
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /Users/mohd/Music/opencv-3.1.0/modules/imgproc/src/color.cpp:7456: error: (-215) scn == 3 || scn == 4 in function ipp_cvtColor

**Comment by codecolony** [comment]
YOu're probably trying to use monochrome image as input. Try color image.

**Comment by NewHope2016** [comment]
Finaly the code work with me. Thank you for your valuable help @codecolony

**Comment by lluisgomez** [comment]
@codecolony Thank you!
